import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Componant/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/Componant/Footer";
import { AuthProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
<AuthProvider>
        <Header/>
        {children}
        <Footer/>
        </AuthProvider>
        </body>
    </html>
  );
}
